### ISSUE TITLE
Clarification about mandatory Flag in Produce Class  

### ISSUE THREAD

**Issue by Gsantomaggio** [celery/kombu#1039]
Hi, 
Why  the `mandatory` flag is marked as `not_supported` on the [documentation](https://kombu.readthedocs.io/en/stable/userguide/producers.html#reference) and inside the [code](https://github.com/celery/kombu/blob/4.2/kombu/messaging.py#L129)?

I tried it and  seems to work correctly:

env:
```
pip freeze
amqp==2.4.2
kombu==4.5.0
PyAMQP==0.0.7.1
...
```

code:
```python
from __future__ import absolute_import, unicode_literals

from kombu import Connection, Producer


def on_return(exception, _exchange, routing_key, _message):
    print("Exception: %s, routing_key: %s" % (exception, routing_key))


with Connection('amqp://guest:guest@localhost:5672//') as connection:
    producer = Producer(connection, on_return=on_return)
    producer.publish({'hello': 'mandatory'}, mandatory=True,
                     routing_key='queue_does_not_exist')
```

result:
```
Exception: Basic.return: (312) NO_ROUTE, routing_key: queue_does_not_exist
```

`312 NO_ROUTE` is exactly the [AMQP error code](https://www.rabbitmq.com/amqp-0-9-1-errata.html#section_17)

Thank you

**Comment by auvipy** [comment]
PR is welcome

**Comment by Gsantomaggio** [comment]
@auvipy thank you,
I am asking why the `mandatory` flag is considered `not_supported`.
I will be glag to make a PR to remove the info on the documentation, but I'd like to know your opinion on it.

**Comment by matteius** [comment]
@Gsantomaggio the answer is because mandatory flag was added in 2010 by @ask and added to the docstrings as not supported and passed along all the way into the transports basic_publish kwargs and then never used within kombu, but the kwargs are sometimes passed for example in the virtual base transport it passed it to self._put which seems to ignore it, but perhaps some transport has been implemented that could use a mandatory flag?  I am not sure the intention but it kind of feels like something that isn't mandatory and could be removed from the code base if you ask me.

# anon exchange: routing_key is the destination queue
return self._put(routing_key, message, **kwargs)
