### ISSUE TITLE
Kombu 4.6.4 breaks celery inspect

### ISSUE THREAD

**Issue by olemoign** [celery/kombu#1081]
Hi,

It had been mentioned that kombu 4.6 was breaking celery workers pings: https://github.com/celery/kombu/issues/1052
The guilty code was reverted, then, in 4.6.4, the revert has been reverted. https://github.com/celery/kombu/commit/052f7601d3a1e09263cc0ebda7ef8c16e6b90175

And ... celery workers pings are broken again.

I'm on holidays, I would be happy to help if I can be of assistance.

**Comment by arikfr** [comment]
Same thing happened to us as well. 

It's somewhat worrying that the revert was reverted without actually checking that the issue was re-introduced, considering how core this functionality is.

**Comment by auvipy** [comment]
we need to find a better solution

**Comment by matteius** [comment]
I was just researching the same ticket on the other side and came to the same conclusion -- I don't quite understand the chain of events because I followed the latest commit of what I saw the obvious code change was in the redis module and it lead me through these two revision loops.  So .. what would give me confidence is understanding why the current code in 4.6.4 is calling new method _lookup_direct that did not exist in 4.6.3 -- in 4.6.4 _lookup_direct has two implemtnations, one in base and one in redis but prior it all just called the one _lookup method that still exists in base.

**Comment by matteius** [comment]
I am going to X-Post this to the other thread as well because it is clear that this is why the logging message doesn't occur (there is no log in the redis version).

`# Calls From Base (4.6.3)
def _lookup(self, exchange, routing_key, default=None):
    """Find all queues matching `routing_key` for the given `exchange`.

    Returns:
        str: queue name -- must return the string `default`
            if no queues matched.
    """
    if default is None:
        default = self.deadletter_queue
    if not exchange:  # anon exchange
        return [routing_key or default]

    try:
        R = self.typeof(exchange).lookup(
            self.get_table(exchange),
            exchange, routing_key, default,
        )
    except KeyError:
        R = []

    if not R and default is not None:
        warnings.warn(UndeliverableWarning(UNDELIVERABLE_FMT.format(
            exchange=exchange, routing_key=routing_key)),
        )
        self._new_queue(default)
        R = [default]
    return R

# Calls From Redis file now (4.6.4)
def _lookup_direct(self, exchange, routing_key):
    if not exchange:
        return [routing_key]

    key = self.keyprefix_queue % exchange
    pattern = ''
    queue = routing_key
    queue_bind = self.sep.join([
        routing_key or '',
        pattern,
        queue or '',
    ])
    with self.conn_or_acquire() as client:
        if client.sismember(key, queue_bind):
            return [queue]

    return []
`

**Comment by matteius** [comment]
@auvipy You might still be online, if so, I am in the middle of updating my PR for the redis issues -- I do have a quesiton for you as I finish my refactor.  I think I have captured the spirit of your original change, but I wanted to ask about calling sismember  -- In redis the s would signify this data structure is a set -- but I would totally think of a queue transport to be a list based implementation -- in Rabbit you can publish a similar message more than once and its not considered a duplicated and with a single worker on average its going to be FIFO without guarantees.  A set in Redis does not behave this way -- does all of the redis queuing logic use sets?  (I am reading through the code to try and answer this now).  You wrote, and I understand the client is basically a StrictRedis client:
```
    with self.conn_or_acquire() as client:
        if client.sismember(key, queue_bind):
            return [queue]
```

**Comment by matteius** [comment]
Ah-ha actually _put does use a list -- it uses lpush.  So using a set is not quite it -- if it were a set we could do:
```
if client.sismember(key, queue_bind):
    return default
else:
   # Lookup member in set
```
However this a list implementation in put ....

**Comment by matteius** [comment]
Nevermind again, it uses everything, lists, sets, sorted sets, Hashes ...
