### ISSUE TITLE
Is there a reason for \x06\x16 to be used as priority separator?

### ISSUE THREAD

**Issue by teferi** [celery/kombu#422]
It makes it really difficult to query redis from command line. 

I tried `redis-cli type "queue_name\x06\x163"` and many other variants with some sort of escaping, but couldn't make it work. 
Also as far as I understand the naming convention in redis is to use ':' as a separator. [redis.io](http://redis.io/topics/data-types-intro)

Could we maybe make it configurable via an environment variable or otherwise?

**Comment by mlissner** [comment]
I just ran into this too, and on a whim googled for `\x06\x163`. I'm happy I found this ticket.

This is causing problems for me because I have [a `CeleryThrottle` class][ct] that can be put into a batch processing loop like so:

```python
throttle = CeleryThrottle(q='some_queue')
for item in really_long_list:
    throttle.maybe_wait()
    process_item.delay(item)
```

The idea is that it prevents a runaway Celery queue when processing millions of items. It does this by preventing the loop from proceeding until the queue is sufficiently short (100 items by default). Without the throttle, millions of tasks get added to redis all at once, and things go ka-boom.

The way the throttle works is to periodically query redis to see how long the queue is, but with this weirdness going on, I'm not sure I understand what key to query in redis. 

Until this is fixed, is there a clear answer to that question? Will the key in redis always be named after the queue or after the queue + `\x06\x16`?

Thanks.

[ct]: https://github.com/freelawproject/courtlistener/blob/48d6f9c45a97a0604dbf4d99e554f1c48d50b690/cl/lib/celery_utils.py#L25

**Comment by georgepsarakis** [comment]
@mlissner perhaps getting the [current worker state](http://docs.celeryproject.org/en/latest/userguide/workers.html?highlight=revoke#inspecting-workers) can help you achieving this.

**Comment by mlissner** [comment]
@georgepsarakis No, that only lets you see what the workers have, not what is in the queue. There's no official way to see what's in the queue that I've been able to find.

**Comment by georgepsarakis** [comment]
The flower project seems to have a solid implementation of what you want probably, see [here](https://github.com/mher/flower/blob/master/flower/utils/broker.py#L135).

**Comment by mlissner** [comment]
@georgepsarakis That's marvelous, thank you very much for this pointer.

**Comment by georgepsarakis** [comment]
@mlissner you are welcome, hope it helps!

**Comment by mlissner** [comment]
This raises an issue [with the documentation][docs], which says that you can use the following to get the number of tasks in a queue:

    $ redis-cli -h HOST -p PORT -n DATABASE_NUMBER llen QUEUE_NAME

We should tweak these docs to mention that that query will only return P0 tasks.

[docs]: http://docs.celeryproject.org/en/latest/userguide/monitoring.html#monitoring-redis-queues

**Comment by jobec** [comment]
If anyone would like to change this behavior. You can monkey patch it like this (on your own risk 😇 ):

```
import kombu.transport.redis
kombu.transport.redis.Channel.sep = ":"
```
Put it before you instantiate your celery app.
