### ISSUE TITLE
Add Boto3 support for use with SQS

### ISSUE THREAD

**Issue by leesdolphin** [celery/kombu#592]
We are running Celery on AWS and using SQS to provide the queue. We use `boto3` in other parts of the project and would prefer not to effectively duplicate dependancies by including both `boto` and `boto3`.

I would like to work towards adding support for `boto3` into Kombu in such a way that both `boto` and `boto3` can be used interchangeably(along the lines of tying `boto3` and falling back to `boto`). Is this be something that the project is interested in?

I have not investigated too deep into this, and will try to investigate this week.

**Comment by ask** [comment]
For sure, if you can contribute that it would be very welcome!

**Comment by golgoth31** [comment]
Hello,
i have modified the SQS.py from tag v3.0.35 (the one given with celery) to use boto3 and not boto. I give it here. Hoping it will help.
If i have some time, i will try to integrate boto3 in the master (many things have changed ...)

thanks for the job

[SQS.txt](https://github.com/celery/kombu/files/318928/SQS.txt)

**Comment by rubendura** [comment]
Without this we can't easily run Celery on ECS using TaskRoles, which means that we need to set an IAM Role for the instance instead of the task, giving permission to all containers in those instances to access our celery queues.

Unfortunately I am not familiar with the kombu codebase so I won't be able to work on this myself.

**Comment by ashb** [comment]
Fixed by #678 (which has been merged)
