### ISSUE TITLE
Kombu on Redis dropping messages

### ISSUE THREAD

**Issue by Shookit** [celery/kombu#593]
I originally posted this on SO, but I realized that this works fine on RabbitMQ, so I wanted to file an actual bug on this:

I'm putting together a producer/consumer setup using Kombu on Redis, but I'm running into an issue. If I start up a consumer and then launch the producer with range(10000), I can confirm that the producer has queued all 10k items, but not all 10k items are received by the consumer. Also, the messages don't seem to come in the produced order, but it does on RabbitMQ.

Is there a limitation I'm not aware of, either with Kombu or Redis? It seems to work correctly with range(9000), and all of the keys/acks have drained properly.
```

class ProduceConsume(object):
    def __init__(self, exchange_name):
        exchange = Exchange(exchange_name, type='fanout', durable=False)
        self.queue_name = 'test_queue'
        self.queue = Queue(self.queue_name, exchange)

    def producer(self, inp):
        with BrokerConnection("redis://localhost:6379/15") as conn:
            with conn.SimpleQueue(self.queue) as queue:
                for payload in inp:
                    queue.put(str(payload).zfill(5))
                    print(str(payload).zfill(5))

    def consumer(self):
        with BrokerConnection("redis://localhost:6379/15") as conn:
            with conn.SimpleQueue(self.queue) as queue:
                while True:
                    message = queue.get()
                    message.ack()
                    print(message.payload)
```

**Comment by ask** [comment]
Thanks for reporting this.

It applies to fanout exchanges only, as direct exchanges receive all the items.

The issue seems to be in the event loop, where it:

- pools the redis socket for readable status
- if the socket is readable, call client.parse_response to receive the PUBSUB message
- yield back to the event loop

The problem occurs when there is more than one PUBSUB message to receive, as something
seems to be consuming this data but it's not given to kombu.  I'm guessing an unrelated command in the redis client receives the data, but ignores it rather than queueing it in a buffer.

I have a fix that solves the issue, but since we have to drain PUBSUB messages until `connection.can_read()` is False we will block the event loop indefinitely until the the events are drained.

**Comment by Shookit** [comment]
Awesome, glad there's a log of this in that case

**Comment by vlcinsky** [comment]
I had exactly the same problem and the cause was as described here: I had one instance of obsolete application running in background messing up with redis queue.

Renaming the queue resolved the problem.

So this does not seem to be a problem with kombu or Redis.
