### ISSUE TITLE
redis transport _on_connection_disconnect expects to be called after .close() but is called other times

### ISSUE THREAD

**Issue by lambacck** [celery/kombu#623]
This is related to #550 or possibly a dup but opening this because #550 seems to be long dead. I could post a similar stack trace as from that issue but I have new information. There seems to be an interaction between `_brpop_read` which disconnect's a connection ultimately calls `_on_connection_disconnect`. `_on_connection_disconnect` appears to be only validly called after `.close()` so `_brpop_read` ultimately gets an unhandled `redis.exceptions.ConnectionError`. Anyway it looks like `_brpop_read` is supposed to be resilient to Redis connection issues but as is in 3.0.x it isn't.

**Comment by mkuchen** [comment]
Thanks for your help @lambacck - this bug has caused quite a few headaches for me and several of my coworkers.

**Comment by ask** [comment]
If brpop raises a connection error that means the connection is unusable, so the connection should be removed from the event loop.  The problem is that redis-py calls automatically calls .disconnect for you in some places, so we have to patch the connection to add this step.

Currently it doesn't just remove the fd from the event loop, it also shuts down the consumer.

If brpop_read raises, in what cases can we continue? The normal way for celery to handle broker connection errors is to restart everything as message ids etc are local to that connection only, so you cannot ack a message received on a different connection.  In redis this is not the case, so maybe we should just continue with a different connection.

**Comment by smartb-pair** [comment]
Would we get a better experience switching away from Redis to RabbitMQ?

**Comment by ask** [comment]
Or maybe more briefly explained:

redis-py disconnects the connection if an error occurs while performing network operations
such as `client.parse_response` and automatically replaces it with a new one.

When this happens maybe we can:

1) Remove the fd from the event loop since it's no longer active
2) Register the new fd in the event loop and send the BRPOP/LISTEN command
    again (depending on the if the connection is used for brpop tasks, or pubsub)

**Comment by ask** [comment]
@smartb-pair Most likely you will, Redis is like the square peg in the RabbitMQ round hole.

**Comment by smartb-pair** [comment]
I wondered about this. Our use of Celery ballooned a bit after our first simple implementation with Redis, so maybe we're pushing the envelope a little bit too far now. Will discuss how we can try Rabbit with the team.

**Comment by lambacck** [comment]
Something changed in the way this is handled at the point I listed in #550. It's reliable before those changes and it just keeps raising connection error and crashing after those changes. This leads me to believe that something (celery or kombu) is not compatible with it.

There is a whole huge thread of users (#550) pasting the same stack trace over and over. It's not just that we should all be using RabitMQ. There is some incompatibility that is not accounted for. I'd like to be able to provide a patch but I can't tell what the right answer is from the existing code.

**Comment by lambacck** [comment]
Re-reading your comment @ask I think the key is that before the change it tried to let another connection go and after it raises a connection error which means that it doesn't. Also this behaviour looks like it only affects the Async path.

**Comment by ask** [comment]
Please try the fix in 47d2ec9, but not that it requires celery 4.

It's a more radical change in that we are relying on the default redis-py connection pool behavior, and only manually create connections for the clients used for reading asynchronously (the client used for BRPOP, and the client used for PUBSUB). 

I tested it using the stress tests and it's working fine for now, but this is a local redis instance, and that will usually magically work.  I tested with `timeout 1` in the redis configuration.
