### ISSUE TITLE
use single connection in ConsumerProducerMixin

### ISSUE THREAD

**Issue by bedwards** [celery/kombu#625]
I am probably misunderstanding something, but why not reuse the "consumer" connection -- the one provided to [on_consume_ready](https://github.com/celery/kombu/blob/master/kombu/mixins.py#L187) -- as the producer connection in [ConsumerProducerMixin](https://github.com/celery/kombu/blob/master/kombu/mixins.py#L256).

Thanks!

**Comment by ask** [comment]
I definitely understand why this is confusing, but connection objects have a dual purpose in that they
both describe the parameters of a connection, and acts as a connection so it kind of makes sense that way (and it means it won't mutate the callers connection).

It also makes sure nothing else will use that connection (for thread-safety, etc), but in hindsight that
is maybe being over-protective.

I would like to clean up the mess that is ConsumerMixin, especially the way it uses with-statements as it turns out using with statements to start an arbitrary list of contexts is not a good pattern, and it only really works for ephemeral things like `with open(...)`.

Possibly it shouldn't be a mixin at all, but simply be a class you instantiate/subclass.

**Comment by ask** [comment]
Btw, the producer-consumer uses two connections by default simply because this is the best practice.

The broker may flow-control connections if there's low disk-space or low memory, but if the producer and consumer uses the same connection then both connections will be blocked.

If they use separate connections the consumer may resolve the situation, unblocking the producer connection again.

**Comment by bedwards** [comment]
Thanks for the explanation. I think it is best to close this issue.
