### ISSUE TITLE
Consumer closes but connection remains

### ISSUE THREAD

**Issue by scheler** [celery/kombu#633]
I am using ConsumerMixin to consume messages from a queue. After a while, we stop receiving any messages. From the rabbitmq management page, I see that there are no consumers listed under the queue. However, using netstat I can see the underlying TCP connection still in established state, and I dont see any errors from the application either.

I have a log statement in on_consumer_end of the ConsumerMixin class, and I dont see it printed.  Shouldn't this callback be called when consumers close?

Any ideas what could be going on?

In case it matters to know, both the client and rabbitmq-server are running in two separate docker containers. I am using pyamqp transport.

**Comment by ask** [comment]
If it doesn't call on_consumer_end, then it's likely that your consumer wasn't able to detect that the connection was closed.  Did it log that the connection was closed at all?

In some network environments connections can be kept alive by intermediate routers, etc. which is why AMQP has the protocol level heartbeats.

You can enable heartbeats, but then you also need to send a heartbeat at the configured intervals or the connection will be closed.  This is difficult in synchronous Python applications, but easily achieved when using gevent/eventlet.

**Comment by scheler** [comment]
Actually, the tcp connection to rabbitmq server isn't closed as I can see it under netstat on the machine where the consumer is running.  Have you seen a case before where the connection exists but the consumers end?

**Comment by kindule** [comment]
Hi, @scheler I tested with the minix and the test code below, and the connection closed after the worker.should_stop = True. And the on_consume_end has log printed.

https://gist.github.com/kindule/1f33306f5529457d4e8f8b5c0ff23afc

Or can you put your code here so we can see where the difference is.

**Comment by mattbennett** [comment]
We are experiencing this problem as well, with kombu==3.0.37 and py-amqp==1.4.9.

The consumer connection is definitely still alive because we have heartbeats enabled.

Poking around in the channel instance I can see the callbacks for consumers that presumably used to exist, but there are no consumers with matching tags on the broker.

**Comment by auvipy** [comment]
hope this is gone with 4.1+ release
