### ISSUE TITLE
Vine missing in pip requirements ?

### ISSUE THREAD

**Issue by lukapeschke** [celery/kombu#641]
When installing kombu with pip in a virtualenv, vine is not installed, causing tox jobs to fail.

**Comment by ask** [comment]
Hey,

I'm pretty sure this means you're attempting to install the wrong version, but possibly that is happening because you're running a broken version of `pip`.

For Celery 4 the requirements are:

Celery 4.0rc6 -> Kombu 4.0 -> amqp 2.0 -> vine

but for Celery 3.1 you should be using:

Celery 3.1 -> Kombu 3.0.x -> amqp 1.4.x

The Celery 3.1 requirements explicitly state that Kombu 4.0 should not be used, but your project
may override this by doing something like:

requirements.txt:
```
celery
kombu
```

You should only depend on celery directly, and not on sub-dependencies.  You should also pin
versions (by range for a library, by specific version for a deployment):

requirements.txt:
```
celery==3.1.25
```

**Comment by lukapeschke** [comment]
Thank you for your quick answer!
Actually, the issue sems to come from oslo.messaging, the requirements.txt file looks like this:

`# we set the amqp version to ensure heartbeat works
amqp<2.0,>=1.4.0 # LGPL
kombu>=3.0.25 # BSD`

What would be the best way to solve this ? Adding vine to this requirements file or specifying kombu<4.0 ?

**Comment by ask** [comment]
The best solution would be for `oslo.messaging` to use:

```
kombu>=3.0.25,<4.0
```

You may also keep the amqp line there, I think that was added to fix some bug in pip.

But kombu should definitely have an upper bound so you don't accidentally upgrade to a major new version accidentally.

PS: amqp 2.0 is licensed under BSD now!

**Comment by jjahns** [comment]
You'll have to check the upper-constraints.txt file in the openstack requirements to make sure that it does not select 4.0.  If it does, then that's an urgent fix, since this breaks all projects and we're supposed to be using the upper-constraints to ensure functionality does not break.
