### ISSUE TITLE
Use passwords passed in "redis+socket://" URLs.

### ISSUE THREAD

**Issue by lddubeau** [celery/kombu#677]
This is the same issue as #460 but happening in the 4.x series now. Steps to reproduce and workarounds are the same as in the earlier bug report, and I suspect the code fix is similar, if not identical.

### Versions

Kombu version: 4.0.2
OS: Debian testing up to date as of 2016-12-28.

**Comment by tkram01** [comment]
I see the same thing.

**Comment by georgepsarakis** [comment]
It seems that the [change](https://github.com/celery/kombu/commit/d720d33a9b6be617d9e083f639b0159cdd00ebae) with the fix is somehow not anymore present in the [master branch](https://github.com/celery/kombu/blob/master/kombu/transport/redis.py#L897). 

@lddubeau yes the fix should be the same probably, but a simple unit test that covers this issue should also be added.
