### ISSUE TITLE
Change Format of Logger?

### ISSUE THREAD

**Issue by prof-schacht** [celery/kombu#712]
Hi Everybody,

I try to change the output of the logger (from kombu.log import get_logger as kombulogger)
to the following format: 
LOG_FORMAT = ('%(levelname) -10s %(asctime)s %(name) -30s %(funcName) '
              '-35s %(lineno) -5d: %(message)s')

But I have no Idea how to do this. Could somebody give me a hint to get this output format for the debug logging working using the get_logger library?

Thanks

**Comment by georgepsarakis** [comment]
You can look at the function [setup_logging](https://github.com/celery/kombu/blob/master/kombu/utils/debug.py#L14) on setting the log level to DEBUG.

In order to change the log format you will need to modify the log handler to use a Formatter class with your pattern, see this [StackOverflow answer](http://stackoverflow.com/a/6888270/920374).

**Comment by georgepsarakis** [comment]
@prof-schacht did you try anything from the above? Let me know if you need more help.
