### ISSUE TITLE
Support for `prefetch_count` in ConsumerMixin

### ISSUE THREAD

**Issue by grantstephens** [celery/kombu#833]
I would like to use the `CosumerMixin` class with a prefetch count, i.e. when defining the `get_consumers` function and giving it a `prefetch_count` a `TypeError` is raised as `prefetch_count` is an unexpected argument, i.e:
```python
    def get_consumers(self, Consumer, channel):
        return [Consumer(
            queues=[self.queue],
            accept=[self.serializer],
            callbacks=[self.process_task],
            prefetch_count=[self.prefetch_count],
            )]
```
(I tried it as a list or just a value). Raises:
```python
TypeError: __init__() got an unexpected keyword argument 'prefetch_count'
```

**Comment by iogakos** [comment]
`prefetch_count` was added in c06eabd4. You need kombu>=4.0.0 to use it.

**Comment by grantstephens** [comment]
I'm on 4.1.0, and it works with a consumer I make myself, but I can't used the ConsumerMixin class- unless I cam doing something wrong.

**Comment by iogakos** [comment]
The `Consumer` argument passed in `get_consumers()` is just a partial `kombu.messaging.Consumer` object frozen at `ConsumerMixin.Consumer()` instance method. The error should be raised by the constructor of that partial object. If not, you are probably using a different Consumer instead of the built-in one. A more detailed stacktrace might be more insightful.  

btw, `prefetch_count` should be an integer.

**Comment by grantstephens** [comment]
Thanks @iogakos seem to have it working now- not sure what changed though. Sorry for wasting time.
