### ISSUE TITLE
Float message priority

### ISSUE THREAD

**Issue by lazuka13** [celery/kombu#967]
Hello!
Do you have any plans about making message priorities float, not integer? I'm talking specifically about Redis transport, where multiple lists created for every queue to support message priorities. But it seems to me that using sorted sets and BZPOPMIN instead of BRPOP can allow to use float priorities (which is actually needed in some cases) and get rid of multiple lists, using just one sorted set. 
I'm planning to use sorted sets myself for my tasks (by rewriting part of transport/redis.py)

**Comment by georgepsarakis** [comment]
Could you please elaborate on a use case where float and not integer priorities are needed? Also, I don't think that with ZADD elements with the same priority will retain their sequence, and this might be a major difference with Lists. Additionally, we must ensure that messages are unique, which I think is a valid assumption to the random task identifier, applied to each message.

**Comment by lazuka13** [comment]
About our use case: 

We have a system that allows users to perform certain tasks in database, these tasks are predefined and we use Celery to create tasks and send them to workers. Right now we need a way to make tasks created by certain users more important than others (for monitoring purposes), and later we're planning to calculate user's tasks priority based on their activity (like, when user starts to create more and more tasks and they just get smaller and smaller priority levels). And it looks that it is much easier to achieve such behaviour with float priorities, not integer.

About ZADD and tasks sequence:

Yes, there is a difference, but in our case "correct" tasks sequence is not important, and maybe it isn't important for some other people as well? I suggest we give users a choice, if they want to have correct tasks sequence and are ok with integer priorities - BRPOP and lists, and if they don't really care about tasks sequence and need float priority - BZPOPMAX and float.

And could you please tell me a bit more about "random task identifier", what is the problem with it when using ZADD?

**Comment by georgepsarakis** [comment]
For your use case, I can suggest distributing the priority to the message priority range 0-255 (the available range is seen [here](http://docs.celeryproject.org/en/latest/userguide/calling.html?highlight=priority#advanced-options)):

```python
int(255 * float_priority / max_float_priority)
```

Additionally, you can also use multiple queues (`high`, `medium`, `low`) and have different workers listen to different queues (more workers processing from the `high` queue and so on). Then you could route messages to a different queue as well and achieve an even wider range of prioritization.

As far as I understand, the Redis transport design tries to follow the AMQP semantics, defined in RabbitMQ, which is why Lists were used and not Sorted Sets.

> And could you please tell me a bit more about "random task identifier", what is the problem with it when using ZADD?

If you use a Set to store messages, the message must be guaranteed to be unique, otherwise you will lose some messages.

**Comment by georgepsarakis** [comment]
@lazuka13 unless you have any further questions, I think we can close this.
